### ISSUE TITLE
java.io.IOException: Cannot run program "D:\platform-tools": CreateProcess error=5, 拒绝访问。

### ISSUE THREAD

**Issue by AotoriChiaki** [lingfengsan/MillionHero#12]
java.io.IOException: Cannot run program "D:\platform-tools": CreateProcess error=5, 拒绝访问。
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:635)
	at java.base/java.lang.Runtime.exec(Runtime.java:459)
	at java.base/java.lang.Runtime.exec(Runtime.java:356)
	at Phone.getImage(Phone.java:27)
	at Main.run(Main.java:42)
	at Main.main(Main.java:26)
Caused by: java.io.IOException: CreateProcess error=5, 拒绝访问。
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 more
获取图片失败

很久不知道为什么……

**Comment by lingfengsan** [comment]
检查下本地中是否有图片呢。可能是adb获取时候出错了。设置sleep的时间较短。

**Comment by GavinLi369** [comment]
应该是你设置的adb路径有问题，你改成“D:\platform-tools\adb”再试试。

**Comment by AotoriChiaki** [comment]
感谢回复，应该改成D:\platform-tools\adb

提取图片没问题了

虽然现在又有Failed loading language 'chi_sim'的问题就是了233

**Comment by AotoriChiaki** [comment]
Failed loading language 'chi_sim'修复了

解决方案是要手动把tessdata文件夹扔到C:\Users\用户名\AppData\Local\Temp\tess4j

运行成功，接下来就是正确率的问题了……
